Adding Model file for Forums database
redhat-beyond/AcadeMe pull request #31
Opened 2021-11-14 17:55 UTC by DanWaldman

2021-11-14 18:11 UTC, DanWaldman commented
HELP
I do not understand why ForumModel won't import from UserModel, tried uploading them together but still didnt work, what can I do?

2021-11-14 21:06 UTC, Yarboa commented
> HELP I do not understand why ForumModel won't import from UserModel, tried uploading them together but still didnt work, what can I do?

Did you run flake tests on your local vm?

2021-11-15 10:08 UTC, Yarboa reviewed
In general
* Please add migration files to migration dir
* see my review for the verification of your code 
* once it will pass CI, add tests

2021-11-15 10:08 UTC, Yarboa commented on AcadeMeData/ForumModels.py
> +from UserModels import *
please replace this line with the following line:
rom django.db import models
from django.conf import settings

to verify and search for hints 
while your vm is up, vagrant ssh
cd /vagrant
run the following:

pipenv run flake8 --max-line-length 120
and check there are no errors

2021-11-15 12:30 UTC, Omeramsc requested changes
Please add tests and an informative commit / PR message, including the issue it is addressing.

2021-11-15 12:30 UTC, Omeramsc commented on AcadeMeData/ForumModels.py
> +    ID = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
Variable names / fields should be in lower case letters (apply to all)

2021-11-15 12:30 UTC, Omeramsc commented on AcadeMeData/ForumModels.py
> +    Rate = models.CharField(max_length=1, choices=range(1-5), default=3)
`rating` may be a better name

2021-11-15 12:30 UTC, Omeramsc commented on AcadeMeData/ForumModels.py
> +    Rate = models.CharField(max_length=1, choices=range(1-5), default=3)
and do we want to have a default rating of 3? seems like it is better be defaulted as None

2021-11-16 06:55 UTC, Yarboa commented
What is the difference between this PR and #30 they have the same name :/

2021-11-22 17:08 UTC, closed without merging