Added models.py file and University class within it
redhat-beyond/AcadeMe pull request #50
Opened 2021-11-22 17:15 UTC by DeanCivlin

2021-11-23 08:25 UTC, Yarboa reviewed
Please add some methods to University
And than add one or two methods and test it with tests,

You are populating input from migration test file.
You can add a list and/or search method and test it.

Other wise, when tests are running, we have no way to verify that this PR work is really working


**Note**

look at PR tests, 
./AcadeMeData/models.py:3:1: F401 'django.conf.settings' imported but unused
./AcadeMeData/migrations/0001_initial.py:18:121: E501 line too long (148 > 120 characters)

tests should pass oi order to be merged"

**Note**
Add reviewers top right, first, you should add team/project members to review
and then the mentors

2021-11-23 12:02 UTC, DeanCivlin commented
@Yarboa Please review my latest changes.
I know it is not done yet but it would be helpful to receive some guidelines on what and where should I improve the code.

2021-11-23 13:45 UTC, Yarboa commented on AcadeMeData/tests.py
> +    def test_get_university_by_id(self):
Do you think this method makes sense ? 
I would consider searching university by name, for a start

2021-11-23 13:45 UTC, Yarboa commented on AcadeMeData/models.py
> +    def get_university_by_id(university_id):
see my comment below, add filter to search university name and location
WDYT?

2021-11-23 16:06 UTC, DeanCivlin commented
@Yarboa made changes according to your review. please take a look

2021-11-23 17:19 UTC, DanielItkes approved these changes

2021-11-23 19:18 UTC, Yarboa approved these changes
LGTM, good work

2021-11-24 08:38 UTC, Yarboa requested changes
Currently your test, or any test is not running in github,
Please refer how to add tests to workflow

run the following pipenv install --dev pytest-django
add pytest.ini
add .github/workflows/pytest.yml
see last class talk please

2021-11-24 09:17 UTC, bregman-arie requested changes

2021-11-24 09:17 UTC, bregman-arie commented on AcadeMeData/tests.py
> +            'Jerusalem')
Please make Jerusalem an argument the function gets

2021-11-24 09:38 UTC, Yarboa reviewed
Please rebase the PR with upstream

2021-11-25 22:12 UTC, Yarboa commented
> Currently your test, or any test is not running in github, Please refer how to add tests to workflow
> 
> run the following pipenv install --dev pytest-django add modified Pipfiles add pytest.ini add .github/workflows/pytest.yml see last class talk please

Already Merged, please rebase, verify your tests are runing

2021-11-27 12:30 UTC, DeanCivlin commented
Code was merged to other PR. closed due to redundancy.

2021-11-27 12:30 UTC, closed without merging