Added tests for degree model
redhat-beyond/AcadeMe pull request #53
Opened 2021-11-23 15:11 UTC by DanielItkes

The tests are not working when running the pytest command in the VM, hoping to get some feedback as to why.

2021-11-23 15:53 UTC, DanielItkes commented on AcadeMeData/tests.py
> +        assert test_degree.get_name() == 'Reichman University'
Should return false, as th name of the degree is 'Computer Science'.

2021-11-23 15:53 UTC, DanielItkes commented on AcadeMeData/tests.py
> +        assert "Reichman University" in test_degree.universities()
Should return true, as 'Reichmain University' is in the string 'Reichman University'.

2021-11-23 16:26 UTC, Yarboa requested changes
It seems to me as part of PR #52 
Please add the test in that PR, thanks

2021-11-23 16:33 UTC, DanielItkes commented
Hi Yariv it's not part of PR #52, the tests are not working and I've used this PR to get feedback
#52 is crucial for pushing a PR containing Course model (which is already done), as there is a dependancy on Degree model
The tests are not working for me on either one of them (Degree/Course models) because of an error I've documented on Slack

2021-11-23 20:00 UTC, Yarboa reviewed
Please lets continue in PR #52 
The tewst should enter there, since the tests are checking the Model Degree

2021-11-23 21:19 UTC, DanielItkes commented
Okay I'll look into it tommorow, thanks!

2021-11-25 05:56 UTC, DanielItkes commented
Outdated.

2021-11-25 05:56 UTC, closed without merging