Added homepage.html and relevant css file for homepage
redhat-beyond/AcadeMe pull request #94
Opened 2021-12-11 11:48 UTC by razashtar93

I created the folder "landing" and in it created the file homepage.html, this is the landing page.
The file only contain a navbar for now

in the folder static/css created the file hompage.css with the necessary css for homepage.html

also added relevant lines in urls.py and views.py for the homepage to be displayed on vagrant up

2021-12-11 15:20 UTC, DanWaldman approved these changes
LGTM

2021-12-11 18:48 UTC, DanielItkes commented
Nice, good job!

2021-12-11 18:48 UTC, DanielItkes approved these changes

2021-12-12 11:26 UTC, Omeramsc requested changes
Remove the meaningless comments, besides that - LGTM. 
(don't worry about losing old code, since everything is on GH you can always reference it if needed. :) )

2021-12-12 11:26 UTC, Omeramsc commented on AcadeMe/urls.py
> +    # path('', views.landingPage,  name='landing_page'),
comment not needed, should be removed.

2021-12-12 11:26 UTC, Omeramsc commented on AcadeMe/views.py
> +# def landingPage(request):
same.

2021-12-12 11:29 UTC, DeanCivlin commented
@Omeramsc We are trying to figure out how I can contribute code changes to this PR. Since we are working together on this feature.
Should I create a PR to Raz branch and then the changes will appear here?
Thanks

2021-12-12 11:36 UTC, Yarboa commented
> @Omeramsc We are trying to figure out how I can contribute code changes to this PR. Since we are working together on this feature. Should I create a PR to Raz branch and then the changes will appear here? Thanks

Please review git challenge, Hint: *Part 4: Dealing with cross-PR dependencies*

2021-12-13 12:32 UTC, Omeramsc approved these changes
LGTM

2021-12-13 13:02 UTC, DeanCivlin approved these changes
Good job Raz! I took the code you wrote and as decided between us, extended it and pushed another PR with HomePage changes and App Layout addition. (PR #97)

2021-12-13 16:08 UTC, Omeramsc commented on templates/landing/homepage.html
> +                    <option selected>Choose University</option>
Should not be hardcoded, but dynamic

2021-12-13 16:08 UTC, Omeramsc commented on templates/landing/homepage.html
> +            <h3 class="my-1">Choose Degree</h3>
Should not be hardcoded, but dynamic

2021-12-13 17:14 UTC, Yarboa reviewed
Please refer #97 comments it is all the same
Lets try to push 97 to be merged first, or implement my comments from there here.
Thanks

2021-12-14 07:59 UTC, Yarboa approved these changes
There are comments, see comments

2021-12-14 07:59 UTC, merged